DROP PROCEDURE IF EXISTS calcMeanStdDev;
DROP PROCEDURE IF EXISTS calculate;
DROP PROCEDURE IF EXISTS preprocessPyroprints;

DROP PROCEDURE IF EXISTS getStats;
DROP FUNCTION IF EXISTS calcPearson;
DROP PROCEDURE IF EXISTS computeAllSimilarities;
DROP PROCEDURE IF EXISTS computeSimilarities;

DROP PROCEDURE IF EXISTS closestSpecies
