DROP PROCEDURE IF EXISTS calcMeanStdDev;
DROP PROCEDURE IF EXISTS calculate;
DROP PROCEDURE IF EXISTS calcAllFiles;

DROP PROCEDURE IF EXISTS getStats;
DROP FUNCTION IF EXISTS pearsonMatch;

DROP PROCEDURE IF EXISTS closestSpecies
